name: build

on:
  push:

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache faustpp build
        uses: actions/cache@v3
        id: faustpp
        with:
          path: build/faustpp/faustpp
          key: faustpp-${{ matrix.target }}
      - name: touch faustpp build
        if: steps.faustpp.outputs.cache-hit == 'true'
        run: |
          touch build/faustpp/faustpp
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          faust: true

  macos:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache faustpp build
        uses: actions/cache@v3
        id: faustpp
        with:
          path: build/faustpp/faustpp
          key: faustpp-${{ matrix.target }}
      - name: touch faustpp build
        if: steps.faustpp.outputs.cache-hit == 'true'
        run: |
          touch build/faustpp/faustpp
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          faust: true

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache faustpp build
        uses: actions/cache@v3
        id: faustpp
        with:
          path: build/faustpp/faustpp
          key: faustpp-${{ matrix.target }}
      - name: touch faustpp build
        if: steps.faustpp.outputs.cache-hit == 'true'
        run: |
          touch build/faustpp/faustpp
          ln -s faustpp build/faustpp/faustpp.exe
      - name: Build native faustpp
        run: |
          make build/faustpp/faustpp -j $(nproc)
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          faust: true
          pawpaw: true
