name: build

on:
  push:

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: faustpp cache
        uses: actions/cache@v3
        with:
          path: |
            *.deb
            build/faustpp/faustpp
          key: linux-${{ inputs.target }}
      - name: install faust
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq libgl1-mesa-dev libx11-dev libxcursor-dev libxext-dev libxrandr-dev libsndfile1 libmicrohttpd12
          wget -c https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust_2.41.1~ds0-0_amd64.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust-common_2.41.1~ds0-0_all.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/libfaust2_2.41.1~ds0-0_amd64.deb
          sudo dpkg -i *.deb
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true

  macos:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: faustpp cache
        uses: actions/cache@v3
        with:
          path: |
            *.deb
            build/faustpp/faustpp
          key: linux-${{ inputs.target }}
      - name: install faust
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq libgl1-mesa-dev libx11-dev libxcursor-dev libxext-dev libxrandr-dev libsndfile1 libmicrohttpd12
          wget -c https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust_2.41.1~ds0-0_amd64.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust-common_2.41.1~ds0-0_all.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/libfaust2_2.41.1~ds0-0_amd64.deb
          sudo dpkg -i *.deb
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: faustpp cache
        uses: actions/cache@v3
        with:
          path: |
            *.deb
            build/faustpp/faustpp
          key: linux-${{ inputs.target }}
      - name: install faust
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq libgl1-mesa-dev libx11-dev libxcursor-dev libxext-dev libxrandr-dev libsndfile1 libmicrohttpd12
          wget -c https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust_2.41.1~ds0-0_amd64.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust-common_2.41.1~ds0-0_all.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/libfaust2_2.41.1~ds0-0_amd64.deb
          sudo dpkg -i *.deb
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          pawpaw: true

  pluginval:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: faustpp cache
        uses: actions/cache@v3
        with:
          path: |
            *.deb
            build/faustpp/faustpp
          key: linux-${{ inputs.target }}
      - name: install faust
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq libgl1-mesa-dev libx11-dev libxcursor-dev libxext-dev libxrandr-dev libsndfile1 libmicrohttpd12
          wget -c https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust_2.41.1~ds0-0_amd64.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/faust-common_2.41.1~ds0-0_all.deb \
                  https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/libfaust2_2.41.1~ds0-0_amd64.deb
          sudo dpkg -i *.deb
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: pluginval
