name: build

on:
  push:

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache faustpp build
        uses: actions/cache@v4
        id: faustpp
        with:
          path: build/faustpp/faustpp
          key: faustpp-${{ matrix.target }}
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          faust: true

  macos:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache faustpp build
        uses: actions/cache@v4
        id: faustpp
        with:
          path: build/faustpp/faustpp
          key: faustpp-${{ matrix.target }}
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          faust: true

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache faustpp build
        uses: actions/cache@v4
        id: faustpp
        with:
          path: build/faustpp/faustpp
          key: faustpp-${{ matrix.target }}
      - name: Build native faustpp first
        run: |
          make faustpp -j $(nproc)
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          lto: true
          faust: true
